name: CMake

on: [push]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
